export const LANGUAGE_COLORS: Record<string, string> = {
  JavaScript: "#f1e05a",
  TypeScript: "#3178c6",
  Python: "#3572A5",
  Java: "#b07219",
  Go: "#00ADD8",
  Rust: "#dea584",
  Ruby: "#701516",
  PHP: "#4F5D95",
  C: "#555555",
  "C++": "#f34b7d",
  "C#": "#178600",
  Swift: "#F05138",
  Kotlin: "#A97BFF",
  Dart: "#00B4AB",
  HTML: "#e34c26",
  CSS: "#563d7c",
  Shell: "#89e051",
  Vue: "#41b883",
  React: "#61dafb",
}

export const QUOTES = [
  "Let's grow together, one commit at a time.",
  "Every commit tells a story of progress.",
  "From zero to hero, line by line.",
  "Code is poetry, and you are the poet.",
  "Building the future, one push at a time.",
  "Your commits are your legacy.",
  "Great things are built incrementally.",
  "Every line of code is a step forward.",
  "The journey of a thousand apps begins with a single commit.",
  "Coding is not just writing, it's creating.",
  "Your GitHub is your canvas, paint it well.",
  "Small commits, big impact.",
]
